#!/usr/bin/env bash
# Check if all the required parameters are passed
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Disable strict host key checking
export SSH_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp -i "$ssh_key" $file_path $username@$server_ip:~

# Check the exit status of the scp command
if [ $? -eq 0 ]; then
  echo "File transferred successfully!"
else
  echo "Failed to transfer the file."
fi
