#!/usr/bin/env bash

# Check if an argument is provided
if [ $# -lt 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Get the IP address from the argument
ip_address=$1

# Ping the IP address 5 times
for ((i=1; i<=5; i++)); do
    ping -c 1 $ip_address > /dev/null
    
    # Check the exit status of ping command
    if [ $? -eq 0 ]; then
        echo "Ping $i: $ip_address is reachable"
    else
        echo "Ping $i: $ip_address is unreachable"
    fi
done
