#!/usr/bin/env bash
# Script to configure Nginx to listen on port 80 and verify it serves content properly

cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
